### ISSUE TITLE
[Gun Run] - Throw gun from right to left hand and it shoots with right hand gun

### ISSUE THREAD

**Issue by shaneharris** [SideQuestVR/LegendsSDK#28]

**Comment by shaneharris** [comment]
Also gun is still attached after you drop it and still shoots

**Comment by Bald-Man-Gamer** [comment]
Also when reloading the mag, if you push the mag too far into the pistol, the hand with the mag will snatch the pistol. 
The hand you originally had the pistol in will shoot with that trigger, even though it's now in the other hand, similar to the 'throw gun' issue.

**Comment by shaneharris** [comment]
this should be fixed in the latest version releasing today
